/**
 * @tolu/cowork-core — BrowserPod Verification Demo
 *
 * Standalone demo showing how to create verification sessions,
 * simulate the verification lifecycle, and display results.
 *
 * Run: npx tsx src/demo/demo-verifier.ts
 */

import { BrowserPodVerificationService } from '../services/browserpod-service.js';
import type { VerificationResult } from '../types/verification-types.js';

// ─── Sample Next.js App Files ────────────────────────────────────────────────

const SAMPLE_FILES: Record<string, string> = {
  'package.json': JSON.stringify({
    name: 'demo-nextjs-app',
    version: '1.0.0',
    scripts: { dev: 'next dev', build: 'next build' },
    dependencies: { next: '14.0.0', react: '18.2.0', 'react-dom': '18.2.0' },
  }, null, 2),

  'pages/index.tsx': `export default function Home() {
  return (
    <div style={{ padding: '2rem' }}>
      <h1>Tolu Cowork Verification Demo</h1>
      <p>This page was generated by AI and verified in BrowserPod.</p>
    </div>
  );
}
`,

  'next.config.js': 'module.exports = { reactStrictMode: true };',

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'es2017'],
      jsx: 'preserve',
      module: 'esnext',
      moduleResolution: 'node',
      strict: true,
    },
  }, null, 2),
};

// ─── Formatting Helpers ──────────────────────────────────────────────────────

function statusIcon(status: string): string {
  const icons: Record<string, string> = {
    pending: '⏳', running: '⚡', success: '✅',
    failed: '❌', timeout: '⏱️',
  };
  return icons[status] ?? '?';
}

function formatResult(result: VerificationResult): string {
  const lines = [
    `  ${statusIcon(result.buildStatus)} Build: ${result.buildStatus}`,
    `  Success: ${result.success}`,
    `  Duration: ${((result.completedAt - result.startedAt) / 1000).toFixed(1)}s`,
  ];

  if (result.portalUrl) {
    lines.push(`  Portal: ${result.portalUrl}`);
  }

  if (result.error) {
    lines.push(`  Error: ${result.error}`);
  }

  if (result.terminalOutput) {
    const preview = result.terminalOutput.slice(-200);
    lines.push(`  Output: ...${preview}`);
  }

  if (result.testResults?.length) {
    const passed = result.testResults.filter((t) => t.status === 'pass').length;
    lines.push(`  Tests: ${passed}/${result.testResults.length} passed`);
  }

  return lines.join('\n');
}

// ─── Demo Scenarios ──────────────────────────────────────────────────────────

async function runDemo(): Promise<void> {
  console.log('════════════════════════════════════════════');
  console.log('  BrowserPod Verification Demo');
  console.log('════════════════════════════════════════════\n');

  const service = new BrowserPodVerificationService({
    enabled: true,
    defaultTimeout: 60_000,
  });

  console.log(`Service active: ${service.isActive()}\n`);

  // ── Scenario 1: Successful Next.js Verification ──
  console.log('── Scenario 1: Next.js App Verification ──\n');

  const session1 = service.createSession({
    task: 'Verify Next.js app renders correctly',
    files: SAMPLE_FILES,
    command: 'npm run dev',
    framework: 'nextjs',
    timeout: 60_000,
  });

  console.log(`Session: ${session1.id}`);
  console.log(`Framework: ${session1.request.framework}`);

  // Simulate the web UI running the verification
  service.startSession(session1.id);
  service.appendOutput(session1.id, '$ npm install\nadded 127 packages in 3.2s\n');
  service.appendOutput(session1.id, '$ npm run dev\n> next dev\n');
  service.appendOutput(session1.id, '  ▲ Next.js 14.0.0\n  - Local:    http://localhost:3000\n');

  // Simulate Portal URL discovery
  service.setPortal(session1.id, 'https://abc123.portal.browserpod.io', 3000);
  service.completeSession(session1.id, true);

  const result1 = service.getSession(session1.id);
  console.log(formatResult(result1));

  // ── Scenario 2: Failed Build ──
  console.log('\n── Scenario 2: Failed Build Detection ──\n');

  const session2 = service.createSession({
    task: 'Verify Express server starts',
    files: { 'server.js': 'const express = require("express"); app.listen(3000);' },
    command: 'node server.js',
    framework: 'express',
    timeout: 30_000,
  });

  service.startSession(session2.id);
  service.appendOutput(session2.id, '$ node server.js\n');
  service.appendOutput(session2.id, 'ReferenceError: app is not defined\n');
  service.completeSession(session2.id, false, 'ReferenceError: app is not defined');

  const result2 = service.getSession(session2.id);
  console.log(formatResult(result2));

  // ── Scenario 3: Session Listing and Cleanup ──
  console.log('\n── Scenario 3: Session Management ──\n');

  const sessions = service.listSessions();
  console.log(`Active sessions: ${sessions.length}`);
  for (const s of sessions) {
    console.log(`  ${s.sessionId.slice(0, 8)}... ${s.buildStatus} ${s.success ? '✓' : '✗'}`);
  }

  const cleaned = service.cleanup(0); // Clean all inactive
  console.log(`Cleaned up: ${cleaned} sessions`);

  console.log('\n════════════════════════════════════════════');
  console.log('  Demo complete');
  console.log('════════════════════════════════════════════');
}

// ── Entry Point ──
runDemo().catch((err) => {
  console.error('Demo failed:', err);
  process.exit(1);
});
